language: python
python:
- '3.6'
- '3.7'
dist: xenial
sudo: true
services:
- docker
before_install:
- git clone https://github.com/DEX-Company/barge.git
- cd barge
- ./start_ocean.sh --no-brizo --no-pleuston --no-aquarius --no-surfer --no-koi --local-spree-node 2>&1 > barge.log &
- cd ..
- sleep 120
- ./scripts/wait_for_migration_and_extract_keeper_artifacts.sh
install: pip install -U tox-travis
script: tox
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  user: "${PYPI_USER}"
  password: "${PYPI_PASSWORD}"
  skip_cleanup: true
  on:
    tags: true
    repo: DEX-Company/wallet-manager
    python: 3.6
